package com.epam.esm.gcs.persistence.repository;

import java.util.Optional;

/**
 * Basic interface for Repositories with CRD methods (create, read, delete)
 *
 * @param <T> - type of Model
 */
public interface CrdRepository<T> {

    /**
     * Creates model
     *
     * @param model - Model prepared for creating
     * @return Created Model with autogenerated fields.
     */
    T create(T model);

    /**
     * Finds Optional.Model by id. (Optional.empty if model not found)
     *
     * @param id - id Of Model to find
     * @return found Optional.Model or Optional.empty if model not found
     */
    Optional<T> findById(long id);

    /**
     * Deletes Model by id from persistence
     *
     * @param id - id of Model to delete
     */
    void delete(long id);

    /**
     * Checks the existence of Model by id
     *
     * @param id - id to search
     * @return true - if Model with @param id exists, false - if Model with @param id does not exist
     */
    Boolean existsById(long id);
}
